---
title: 
author: 
date: 
output: pdf_document
header-includes: \usepackage{amsmath}
---


\section{Law of Large Numbers}
Suppose we have $x_i: \Omega \rightarrow \mathbb{R}^d \hspace{.3cm} i=1,..., \infty$ variables.


\underline{\textbf{Definition}} (\textit{Identically distributed})\newline
\textbf{(a)} The \textit{law} of $x_i$ is the measure 

\[ 
\mu_i := law(x_i) \ defined \ on \ \mathbb{R}^d \hspace{.2cm}  by  \\ \mu_i[B] = \mathbb{P} \{ x_i \hspace{.2cm} \epsilon \hspace{.2cm} B\}  \hspace{.2cm} \forall  \ B \  \subset \mathbb{R}^d
\]

\textbf{(b)} $x_i$ and $x_j$ are identically distributed if 
\[
law(x_i) = law(x_j) \hspace{.2cm} 
\]

\underline{\textbf{Definition}} (\textit{Independence}) $(x_i)_i^\infty$ are independent for every $i_1,...,i_k$ and every $A_1,...,A_k \subset \mathbb{R}^d$ Borel
\[
P(x_{i1} \ \epsilon \ A_1,..., x_{ik} \ \epsilon \ A_k) = P(x_{i1} \ \epsilon \ A_1) \cdot \cdot \cdot  P(x_{ik} \ \epsilon \ A_k)
\]

\underline{\textbf{Theorem}} (\textit{Law of Large Numbers}) Let $(Z_n)_{n=1}^\infty$ be a random variable, we say that $(z)_n$ converges to z in probability if $\forall \ \varepsilon > 0$

\textbf{(weak law)}
\[
\lim \limits_{n \rightarrow \infty} \mathbb{P}\{|z_n - z| \geq\varepsilon \} = 0 
\]

\textbf{(strong law)}
\[
\lim_{n\rightarrow\infty} z_n=z \hspace{.2cm} a.e 
\]


\textbf{\underline{Proof}}

If $\lim \limits_{n\rightarrow \infty}\mathbb{E}[z_n - z] \implies z_{nk} \rightarrow z$  a.e  for  a  subsequence $(z_{nk})_k$ \newline
Assume we have convergence in probability,

\[ 
\mathbb{E}[z_n - z] = \int_\Omega|z_n - z|d\mathbb{P} 
\]

\[ 
\implies  \mathbb{E}[z_n - z] = \int_{|z_n-z| < \varepsilon}|z_n - z|d\mathbb{P} +  \int_{|z_n-z| \geq \varepsilon}|z_n - z|d\mathbb{P} \ \leq \ \varepsilon \ \mathbb{P}{|z_n - z| < \varepsilon + ... (missed \ what \ was \ written \ here)}
\]

\[
\implies \mathbb{E}[z_n - z] = \int_{|z_n-z| < \varepsilon}|z_n - z|d\mathbb{P} + \int_{\Omega}|z_n - z| \chi^2_{A^\varepsilon _n}d\mathbb{P} \ \leq \varepsilon \  \mu\{|z_n - z|\ \leq \ \varepsilon \} + (\int_\Omega|z_n - z|^2d\mathbb{P})^{\frac{1}{2}}(\int_\Omega \chi^2_{A^\varepsilon _ n}d\mathbb{P})^{\frac{1}{2}}
\]

We get this from Holder's inequality, which says
\[ 
\int_\Omega|fg|d\mathbb{P} \ \leq \ \sqrt{\int_\Omega f^2d\mathbb{P}}\sqrt{\int_\Omega g^2d\mathbb{P}}
\]

Now going back to our equation
\[
\leq \varepsilon \mathbb{P}(\Omega) + \sqrt{\int_n|z_n - z|^2d\mathbb{P}}\sqrt{\mathbb{P}[A^\varepsilon _n]}
\]

\[ 
\leq \varepsilon + \sqrt{2var(z_n) + 2var(z)}\sqrt{\mathbb{P}[A_n^\varepsilon]}
\]

From this we can conclude that if $var(z_n) \leq C$ and $z_n \xrightarrow{p} z$, then 
\[
\mathbb{E}[z_n-z] \  \leq \ \varepsilon + \sqrt{4C} \cdot \mathbb{P}
\]

and so, 
\[
\varlimsup \limits_{n\rightarrow} |z_n - z| \leq \ \varepsilon \ \forall \ \varepsilon
\]

Thus,
\[
\varlimsup \limits_{n \rightarrow \infty} \mathbb{E}[|z_n - z|] = 0
\]


\textbf{\underline{Corollary}} If $z_n \xrightarrow{p} z$  the there exists a subsequence $(z_{nk})_{k=1}^\infty$ which converges to z in probability a.e.

It is important to note that we don't know if the whole sequence converges in probability a.e, so that is why we consider the subsequence.

=========================================================================
If $x_i: \Omega \rightarrow \mathbb{R}^d \hspace{.3cm} i=1,..., \infty$ are independent and identically distributed (iid) then,

\begin{center}
\[ 
\frac{x_1 + ...+ x_n}{n} \cong E(X) \hspace{.2cm} for \ n \ large \ enough
\]
\end{center}
 Additionally, for any two points , $w$ and $a$,
 
 \[
 \frac{x_1(w)+...+x_n(w)}{n} - \frac{x_1(a)+...+x_n(a)}{n} \rightarrow 0 \hspace{.3cm} when \ n \rightarrow \infty
 \]
 except when $a,w \ \epsilon \ N \ and \ P(N)=0$
 
 Essentially, for n large enough if we know the expectation at one point we know the expectation at any other point. 
 
========================================================================== 
 
 The Law of Large numbers is often used in conjunction with the Central Limit theorem.
 
 \underline{\textbf{Theorem}} \textit{(Central Limit Theorem)} (CLT) If $x_1,....,x_n$ is a random sample from a distribution with mean $\mu$ and variance $\sigma^2 < \infty$ then the limiting distribution of 
 \[Z_n = \frac{\sum_{i=1}^nX_i \ - n\mu}{\sqrt{n}\sigma}
 \]
 is the standard normal, $Z_n \xrightarrow{d} Z \sim N(0,1)$ as $n \rightarrow \infty$. \newline
 
 The key idea behind the CLT is that is can be used to approximate a distribution in cases where the exact distribution is unknown or intractable.
 

 
\underline{\textbf{Remarks}} \newline

$\bullet$ n = 30 is sufficiently large for the approximations using the CLT.

$\bullet$ The average of the sample means and standard deviations will equal the population mean and standard deviation.













 
 
 
 
 
 
 