---
title: "Meeting 10-13-23"
author: "Dominique McDonald"
date: "2023-02-17"
output: pdf_document
---

\underline{Dirac Masses} \newline

Suppose $a \hspace{.2 cm} \epsilon \hspace{.2 cm} \mathbb{R}^3(\mathbb{R}^d, X)$ where X is some arbitrary set. \newline

Say We want to know if a particle is in the set E. (include graphic - DJM) \newline


- $\delta_a(E) = 1 \hspace{.3 cm} a \hspace{.2 cm} \in \hspace{.2cm} E$
- $\delta_a(E) = 0 \hspace{.3 cm} a \hspace{.2 cm} \notin \hspace{.2cm} E$


$\delta_a$: a dirac mass concentrated at a

- $\delta_a(\not0) = 0$
- $\delta_a(\cup_{i=1}^\infty E_i) = \sum_{i = 1}^ \infty E_i \hspace{.3 cm} E_i = E_j = \not0 \hspace{.2cm} when \hspace{.2cm} i \neq j$ \newline
-- i.e a can only be present in one. \newline
- $\delta_a[\mathbb{R}^d] = 1$

We want to check if the dirac mass is a probability measure. Often times in probability (??? DJM) we are looking at the average of dirac masses. \newline

\underline{Examples}

- $\mu = \frac{1}{n} \sum_{i=1}^n \delta_{a_i} =  \frac{\delta_{a_1} + \delta_{a_2} + ... + \delta_{a_n} }{n}$ Here we are counting how many particles are in A and dividing by n to average. \newline

- $\mu[A] = \frac{k}{n}$ where k = (number of particles) \newline

\textbf{Notation}

- $\Omega$ : Probability space (a set)

- $\mathbb{P}$ : Probability measure on $\Omega \implies \mathbb{P} : \Sigma \rightarrow [0,1]$
- $\Sigma$ : a $\sigma$-algebra on $\Omega$
- $\mathbb{R}^d$ : a vector space of d dimensions
-  B: borel $\sigma$-algebra on $\mathbb{R}^d$

(add graphic - DJM)

\textbf{Defintions}

- Borel $\sigma$-algebra : the smallest $\sigma$-algebra containing the open subsets in $\mathbb{R}^d$
- Boret Set : any element of a Borel $\sigma$-algebra

\underline{Aside} \newline

$\Theta \subset \mathbb{R}$ is open IFF $\Theta$ is a union of open intervals



\underline{OT broad overview}

1. start with a map $T:\Omega \rightarrow \mathbb{R}^d$ \newline
2. construct a set $B \subset\mathbb{R}^d$ \newline
3. Pull the set back to $\Omega$ to get $T^{-1}(B) \subset \Omega$ \newline
4. Find a probability measure $\mu(B) = \mathbb{P}[T^{-1}(B)]$ where $\mu$ is called the \textit{law} of T



















